name: scheme_web_interpreter
description: Web frontend for cs61a_scheme interpreter.
homepage: https://scheme.cs61a.org
author: Jen Thakar <jthakar@berkeley.edu>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  cs61a_scheme:
      path: ../dart_scheme
  cs61a_scheme_impl:
      path: ../dart_scheme_impl
  dart_to_js_script_rewriter: ^1.0.3

dev_dependencies:
  browser: any
  appcache:
    git: https://github.com/jathak/dart-appcache.git
  transform_sass: ^0.3.1
  test: ^0.12.0

transformers:
  - transform_sass
  - dart_to_js_script_rewriter
