name: scheme_web_interpreter
description: Web frontend for cs61a_scheme interpreter.
homepage: https://scheme.cs61a.org
author: CS 61A Staff <cs61a@berkeley.edu>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  browser: "^0.10.0+2"
  cs61a_scheme:
      path: ../cs61a_scheme
  cs61a_scheme_impl:
      path: ../cs61a_scheme_impl
  dart_sass_transformer: ^0.5.0+1
      

dependency_overrides:
  cs61a_scheme:
      path: ../cs61a_scheme

dev_dependencies:
  test: ^0.12.0
 
transformers:
  - dart_sass_transformer:
      executable: sass
      style: compact
      copy-sources: true
